'use strict';

const { v4: uuidv4 } = require('uuid');
const {faker} = require('@faker-js/faker')

module.exports = {
 async up(queryInterface, DataTypes) {
  await queryInterface.bulkInsert('item', [
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 4,
      itemName: 'Tommy',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 1,
      itemPrice: 3000000,
      itemType: 'pets',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 4,
      itemName: 'Niko',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 1,
      itemPrice: 2500000,
      itemType: 'pets',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 5,
      itemName: 'Mici',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 1,
      itemPrice: 1000000,
      itemType: 'pets',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 5,
      itemName: 'Voni',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 1,
      itemPrice: 1200000,
      itemType: 'pets',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 6,
      itemName: 'Narnia',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 1,
      itemPrice: 5000000,
      itemType: 'pets',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 6,
      itemName: 'Lobra',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 1,
      itemPrice: 4000000,
      itemType: 'pets',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 7,
      itemName: 'Mila',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 1,
      itemPrice: 300000,
      itemType: 'pets',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 7,
      itemName: 'Sola',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 1,
      itemPrice: 500000,
      itemType: 'pets',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 8,
      itemName: 'Tony',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 1,
      itemPrice: 800000,
      itemType: 'pets',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 8,
      itemName: 'Nebula',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 1,
      itemPrice: 400000,
      itemType: 'pets',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 11,
      itemName: 'Royal Canin Maxi Adult Makanan Anjing Dewasa Wet',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 100,
      itemPrice: 300000,
      itemType: 'product',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 11,
      itemName: 'Royal Canin Kitten Makanan Anak Kucing Dry',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 100,
      itemPrice: 150000,
      itemType: 'product',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 12,
      itemName: 'Acis Sticky Roller 30 Layers',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 100,
      itemPrice: 30000,
      itemType: 'product',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 12,
      itemName: 'Baba Dod Shampoo 450ml',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 100,
      itemPrice: 50000,
      itemType: 'product',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 13,
      itemName: 'Active Pro Healthy Growth Formula – Vitamin Untuk Anak Anjing & Kucing',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 100,
      itemPrice: 35000,
      itemType: 'product',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 13,
      itemName: 'Active Pro Multivitamin Immune Booster Uuntuk Anjing & Kucing',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 100,
      itemPrice: 25000,
      itemType: 'product',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 14,
      itemName: 'Cat & Dog Tent Bed – Tempat Tidur Tenda Lucu',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 100,
      itemPrice: 300000,
      itemType: 'product',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 14,
      itemName: 'Dog Cage Single Door Kandang Anjing 40cm',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 100,
      itemPrice: 250000,
      itemType: 'product',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 15,
      itemName: 'Suba Mainan Stik Kerincing Kucing – Pet Toys Stick',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 100,
      itemPrice: 20000,
      itemType: 'product',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      uuid: uuidv4(),
      storeId: 1,
      categoryId: 15,
      itemName: 'Plush Stuffed Fish Catnip Toy – Mainan Boneka Ikan Catnip',
      itemDescription: faker.commerce.productDescription(),
      itemStock: 100,
      itemPrice: 55000,
      itemType: 'product',
      itemStatus: true,
      createdAt: new Date(),
      updatedAt: new Date()
    },
  ], {});
},

  async down(queryInterface, Sequelize) {
  await queryInterface.bulkDelete('item', null, {});
}}
